# Generated by Django 2.2.1 on 2019-06-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('insertion_date', models.DateTimeField(verbose_name='Person insertion date')),
                ('exclusion_date', models.DateTimeField(verbose_name='Person exclusion Date')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='prestadores.Person')),
                ('insertion_date', models.DateTimeField(verbose_name='Supplier insertion date')),
                ('exclusion_date', models.DateTimeField(verbose_name='Supplier exclusion date')),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=4500)),
                ('insertion_date', models.DateTimeField(verbose_name='Expertise insertion date')),
                ('exclusion_date', models.DateTimeField(verbose_name='Expertise exclusion date')),
                ('suppliers', models.ManyToManyField(to='prestadores.Supplier')),
            ],
        ),
    ]
