# Generated by Django 2.2.1 on 2019-06-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='exclusion_date',
            field=models.DateTimeField(null=True, verbose_name='Expertise exclusion date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='exclusion_date',
            field=models.DateTimeField(null=True, verbose_name='Person exclusion Date'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='exclusion_date',
            field=models.DateTimeField(null=True, verbose_name='Supplier exclusion date'),
        ),
    ]
