# Generated by Django 2.2.1 on 2019-06-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestadores', '0002_auto_20190607_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='exclusion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expertise exclusion date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='exclusion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Person exclusion Date'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='exclusion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Supplier exclusion date'),
        ),
    ]
